# Generated by Django 5.2.3 on 2025-06-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('title_skils', models.CharField(max_length=100)),
                ('aria_valuenow', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Skils',
                'verbose_name_plural': 'Skils',
            },
        ),
    ]
