# Generated by Django 5.2.3 on 2025-06-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skils',
            name='description_skils',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
