# Generated by Django 5.2.3 on 2025-06-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skils', '0003_skils_main_remove_skils_description_skils_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='skils_tow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_skils', models.CharField(max_length=100)),
                ('aria_valuenow', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Skils',
                'verbose_name_plural': 'Skils',
            },
        ),
    ]
