# Generated by Django 5.2.3 on 2025-06-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.RenameField(
            model_name='about',
            old_name='image_about',
            new_name='images_about',
        ),
    ]
