# Generated by Django 5.2.3 on 2025-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title_head_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='website_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
