# Generated by Django 5.2.3 on 2025-06-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_about_title_head_line_alter_about_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_bottom_about',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
