# Generated by Django 5.2.3 on 2025-06-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_description_bottom_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_main_about',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
