# Generated by Django 5.2.3 on 2025-06-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_about_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_list',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
