# Generated by Django 5.2.3 on 2025-06-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_downloadcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadcv',
            name='cv_online',
            field=models.URLField(blank=True, null=True),
        ),
    ]
