# Generated by Django 5.2.3 on 2025-06-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_about_list_images_about_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_list',
            name='images_about_list',
            field=models.ImageField(blank=True, null=True, upload_to='list/'),
        ),
    ]
