# Generated by Django 5.2.3 on 2025-07-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_title', models.CharField(blank=True, max_length=254, null=True)),
                ('cont_decription', models.CharField(blank=True, max_length=254, null=True)),
                ('cont_palse', models.CharField(max_length=50)),
                ('cont_phone', models.CharField(max_length=20)),
                ('cont_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'contact main',
                'verbose_name_plural': 'contact main',
            },
        ),
        migrations.CreateModel(
            name='ContactMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_title', models.CharField(blank=True, max_length=254, null=True)),
                ('cont_decription', models.CharField(blank=True, max_length=254, null=True)),
                ('cont_palse', models.CharField(max_length=50)),
                ('cont_phone', models.CharField(max_length=20)),
                ('cont_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'contactmain',
                'verbose_name_plural': 'contactmain',
            },
        ),
    ]
