# Generated by Django 5.2.3 on 2025-06-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skils', '0002_skils_description_skils'),
    ]

    operations = [
        migrations.CreateModel(
            name='skils_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('description_skils', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'main_title',
                'verbose_name_plural': 'main_title',
            },
        ),
        migrations.RemoveField(
            model_name='skils',
            name='description_skils',
        ),
        migrations.RemoveField(
            model_name='skils',
            name='main_title',
        ),
    ]
