# Generated by Django 5.2.3 on 2025-06-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skils', '0004_skils_tow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skils_tow',
            options={'verbose_name': 'Skils-tow', 'verbose_name_plural': 'Skils-tow'},
        ),
    ]
