# Generated by Django 5.2.5 on 2025-08-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skils', '0005_alter_skils_tow_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skils_main',
            name='description_skils',
            field=models.TextField(blank=True, max_length=550, null=True),
        ),
    ]
