# Generated by Django 5.2.3 on 2025-06-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=255, null=True)),
                ('description_about', models.TextField(blank=True, max_length=255, null=True)),
                ('image_about', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('birthday_about', models.DateField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('age_about', models.IntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('freelance_about', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
