# Generated by Django 5.2.3 on 2025-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_about_description_main_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description_main_about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
