# Generated by Django 5.2.3 on 2025-06-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_about_description_main_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_list', models.CharField(blank=True, max_length=255, null=True)),
                ('description_list', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About List',
                'verbose_name_plural': 'About Lists',
            },
        ),
    ]
