# Generated by Django 5.2.3 on 2025-06-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_about_list_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_list',
            name='title_about',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
