# Generated by Django 5.2.3 on 2025-06-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_downloadcv_cv_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadcv',
            name='cv_online',
        ),
    ]
