# Generated by Django 5.2.3 on 2025-06-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_remove_downloadcv_cv_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_list',
            name='images_about_list',
            field=models.ImageField(blank=True, null=True, upload_to='about/list/'),
        ),
    ]
