# Generated by Django 5.2.3 on 2025-07-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('main_description', models.TextField()),
            ],
            options={
                'verbose_name': 'Main Page',
                'verbose_name_plural': 'Main Pages',
            },
        ),
    ]
