# Generated by Django 5.2.3 on 2025-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_one', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'list_one',
                'verbose_name_plural': 'list_one',
            },
        ),
        migrations.CreateModel(
            name='list_tow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_tow', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'list_tow',
                'verbose_name_plural': 'list_tow',
            },
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume')),
                ('title_resume', models.CharField(blank=True, max_length=200, null=True)),
                ('description_resume', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='resume_list_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_list_one', models.FileField(blank=True, null=True, upload_to='resume_list')),
                ('title_main_resume_list_one', models.CharField(blank=True, max_length=200, null=True)),
                ('title_resume_list_one', models.CharField(blank=True, max_length=200, null=True)),
                ('time_Current_resume_list_one', models.CharField(blank=True, max_length=200, null=True)),
                ('time_End_resume_list_one', models.CharField(blank=True, max_length=200, null=True)),
                ('location_resume_list_one', models.CharField(blank=True, max_length=200, null=True)),
                ('description_resume_list_one', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume List One',
                'verbose_name_plural': 'Resume Lists One',
            },
        ),
        migrations.CreateModel(
            name='resume_list_two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_list_tow', models.FileField(blank=True, null=True, upload_to='resume_list')),
                ('title_main_resume_list_tow', models.CharField(blank=True, max_length=200, null=True)),
                ('title_resume_list_tow', models.CharField(blank=True, max_length=200, null=True)),
                ('time_Current_resume_list_tow', models.CharField(blank=True, max_length=200, null=True)),
                ('time_End_resume_list_tow', models.CharField(blank=True, max_length=200, null=True)),
                ('location_resume_list_tow', models.CharField(blank=True, max_length=200, null=True)),
                ('description_resume_list_tow', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resume List Tow',
                'verbose_name_plural': 'Resume Lists Tow',
            },
        ),
    ]
