# Generated by Django 5.2.3 on 2025-06-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_list_one_description_list_resume_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_list_two',
            name='description_list_resume_tow',
            field=models.TextField(blank=True, null=True),
        ),
    ]
