# Generated by Django 5.2.3 on 2025-07-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonials_name', models.CharField(max_length=100)),
                ('Testimonials_Kotation', models.TextField()),
                ('Testimonials_Speciality', models.CharField(max_length=100)),
                ('Testimonials_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Testimonials_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonials_name_main', models.CharField(max_length=100)),
                ('Testimonials_description_main', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimonials main',
                'verbose_name_plural': 'Testimonials main',
            },
        ),
    ]
