# Generated by Django 5.2.3 on 2025-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='site_name',
            field=models.CharField(default='MySite', max_length=100),
        ),
    ]
